image: node:16

cache:
  untracked: true
  key: $CI_PROJECT_ID
  paths: 
    - node_modules/
    - .yarn

before_script:
  - yarn config set cafile $CERT_PATH
  - cp $NPMRC .npmrc
  - yarn config set cache-folder $(pwd)"/.yarn"
  - yarn install

stages:
  - test
  - release

test:
  stage: test
  script:
    - yarn lerna bootstrap
    - yarn prepublishOnly
    - git diff --exit-code

release:
  stage: release
  script:
    - yarn lerna bootstrap
    - yarn prepublishOnly
    - HUSKY=0 yarn lerna publish from-git --yes --registry https://store.inside.sahab.ir/repository/NPM-Phoenix/
  only:
    refs:
      - master
