# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          # we actually need "github.event.pull_request.commits + 1" commit
          fetch-depth: 0
      - name: Use Node.js version 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn run commitlint --from HEAD~${{ github.event.pull_request.commits }} --to HEAD
      - run: yarn lerna bootstrap
      - run: yarn prepublishOnly
      - run: yarn lerna run type:check --stream
